var jsonOutputPreview = [
      {
		 "id": 2300,
         "description": "ID 2300",
		 "checklistType": "contentCreation",
         "outputSPD": true,
         "outputCH": true,
		 "outputGH": true,
		 "outputPDFPrint": true,
		 "outputPDFOnline": true,
         "outputPDF_DITA": true,
		 "outputCHM": true,
		 "outputCHM_DITA": true,
		 "outputReadme": true
      },
	  {
		 "id": 2301,
         "description": "ID 2301",
		 "checklistType": "contentCreation",
		 "leadReviewerCheck": true,
         "outputSPD": true,
         "outputCH": true,
		 "outputGH": true,
		 "outputPDFPrint": true,
		 "outputPDFOnline": true,
         "outputPDF_DITA": true,
		 "outputCHM": true,
		 "outputCHM_DITA": true,
		 "outputReadme": true
      },
	  {
		 "id": 2302,
         "description": "ID 2302",
		 "checklistType": "contentCreation",
		 "leadReviewerCheck": true,
         "outputSPD": true,
         "outputCH": true,
		 "outputGH": true,
		 "outputPDFPrint": true,
		 "outputPDFOnline": true,
         "outputPDF_DITA": true,
		 "outputCHM": true,
		 "outputCHM_DITA": true,
		 "outputReadme": true
      },
	  {
		 "id": 2303,
         "description": "ID 2303",
		 "checklistType": "contentCreation",
		 "outputPDFPrint": true,
		 "outputPDFOnline": true,
         "outputPDF_DITA": true
      },
	  {
		 "id": 2304,
         "description": "ID 2304",
		 "checklistType": "contentCreation",
		 "leadReviewerCheck": true,
         "outputSPD": true,
         "outputCH": true,
		 "outputGH": true,
		 "outputPDFPrint": true,
		 "outputPDFOnline": true,
         "outputPDF_DITA": true,
		 "outputCHM": true,
		 "outputCHM_DITA": true,
		 "outputReadme": true
      },
	  {
		 "id": 2305,
         "description": "ID 2305",
		 "checklistType": "contentCreation",
		 "leadReviewerCheck": true,
         "outputSPD": true,
         "outputCH": true,
		 "outputGH": true,
		 "outputPDFPrint": true,
		 "outputPDFOnline": true,
         "outputPDF_DITA": true,
		 "outputCHM": true,
		 "outputCHM_DITA": true,
		 "outputReadme": true
      },
	  {
		 "id": 2306,
         "description": "ID 2306",
		 "checklistType": "contentCreation",
		 "leadReviewerCheck": true,
         "outputSPD": true,
         "outputCH": true,
		 "outputGH": true,
		 "outputPDFPrint": true,
		 "outputPDFOnline": true,
         "outputPDF_DITA": true,
		 "outputCHM": true,
		 "outputCHM_DITA": true,
		 "outputReadme": true
      },
	  {
		 "id": 2307,
         "description": 'ID 2307',
		 "checklistType": "contentCreation",
		 "leadReviewerCheck": true,
         "outputSPD": true,
         "outputCH": true,
		 "outputGH": true,
		 "outputPDFPrint": true,
		 "outputPDFOnline": true,
         "outputPDF_DITA": true,
		 "outputCHM": true,
		 "outputCHM_DITA": true,
		 "outputReadme": true
      },
	  {
		 "id": 2308,
         "description": "ID 2308",
		 "checklistType": "contentCreation",
		 "leadReviewerCheck": true,
		 "outputGH": true
      },
	  {
		 "id": 2309,
         "description": "ID 2309",
		 "checklistType": "contentCreation",
         "outputSPD": true,
         "outputPDF_DITA": true
      },
	  {
		 "id": 2310,
         "description": "ID 2310",
		 "checklistType": "contentCreation",
		 "outputPDFPrint": true,
		 "outputPDFOnline": true
      },
	  {
		 "id": 2311,
         "description": "ID 2311",
		 "checklistType": "contentCreation",
		 "leadReviewerCheck": true,
		 "outputPDFPrint": true,
		 "outputPDFOnline": true
      },
	  {
		 "id": 2312,
         "description": "ID 2312",
		 "checklistType": "contentCreation",
		 "leadReviewerCheck": true,
         "outputSPD": true
      },
   ]